[package]

name = "ntree"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[dependencies]
ref_slice = "1"
rand = { version = "0.3", optional = true }

[features]
default = []
nightly = []
bench = ["nightly", "rand"]

